import base64
import os
from datetime import datetime, timezone
from pathlib import Path
from importlib import import_module

import pytest


pytest_html = import_module("pytest_html")
metadata_key = import_module("pytest_metadata.plugin").metadata_key


def _report_dir() -> Path:
    """
    Directory supplied by CI for the current test module.
    Falls back to a timestamped local artifacts directory.
    """
    path = os.getenv(
        "REPORT_DIR",
        f"artifacts/{datetime.now().strftime('%Y%m%d-%H%M%S')}",
    )

    directory = Path(path)
    directory.mkdir(parents=True, exist_ok=True)

    return directory


def _classification(item):
    """
    Classification controlled by pytest markers.

    @pytest.mark.ui
    @pytest.mark.visual
    @pytest.mark.functional
    @pytest.mark.logic
    """

    if item.get_closest_marker("ui") or item.get_closest_marker("visual"):
        return "UI / Visual"

    if item.get_closest_marker("functional") or item.get_closest_marker("logic"):
        return "Functional / Logic"

    return "Functional / Logic"


def _impact(item):
    """
    Impact controlled by pytest markers.

    @pytest.mark.p1
    @pytest.mark.p3
    """

    if item.get_closest_marker("p1"):
        return "Critical / P1"

    return "Medium / P3"


def pytest_configure(config):
    if hasattr(config, "stash"):
        config.stash[metadata_key]["Tester"] = "Peru"
        config.stash[metadata_key]["Application"] = "NativeOffice"
        config.stash[metadata_key]["Environment"] = "CI"
        config.stash[metadata_key]["Report Generated"] = (
            datetime.now(timezone.utc).strftime(
                "%Y-%m-%d %H:%M:%S UTC"
            )
        )


def pytest_html_report_title(report):
    report.title = "NativeOffice QA Test Report"


def pytest_html_results_table_header(cells):
    cells.insert(
        2,
        '<th class="qa-area-header">Area</th>',
    )

    cells.insert(
        3,
        '<th class="qa-impact-header">Impact</th>',
    )


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()

    report.area = _classification(item)
    report.impact = _impact(item)

    extras = getattr(report, "extras", [])

    if report.when == "call" and report.failed:

        report_dir = _report_dir()

        screenshot_dir = report_dir / "screenshots"
        screenshot_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        safe_name = (
            item.nodeid
            .replace("/", "_")
            .replace("\\", "_")
            .replace(":", "_")
            .replace("[", "_")
            .replace("]", "_")
        )

        screenshot_path = screenshot_dir / f"{safe_name}.png"

        page = item.funcargs.get("page")

        # --------------------------------------------------
        # FAILURE SCREENSHOT
        # --------------------------------------------------

        if page:
            try:
                screenshot_bytes = page.screenshot(
                    full_page=True
                )

                screenshot_path.write_bytes(
                    screenshot_bytes
                )

                encoded = base64.b64encode(
                    screenshot_bytes
                ).decode("utf-8")

                extras.append(
                    pytest_html.extras.image(
                        encoded,
                        mime_type="image/png",
                        extension="png",
                        name="Failure Screenshot",
                    )
                )

            except Exception as exc:
                extras.append(
                    pytest_html.extras.text(
                        f"Screenshot capture failed: {exc}",
                        name="Screenshot Error",
                    )
                )

        # --------------------------------------------------
        # PLAYWRIGHT FAILURE EVIDENCE
        # --------------------------------------------------

        test_results_dir = report_dir / "test-results"

        if test_results_dir.exists():

            # Failure screenshots generated by Playwright
            screenshots = list(
                test_results_dir.rglob("test-failed-*.png")
            )

            for screenshot in screenshots:

                relative_path = screenshot.relative_to(
                    report_dir
                ).as_posix()

                extras.append(
                    pytest_html.extras.html(
                        f"""
                        <div class="qa-evidence">
                            <a
                                href="{relative_path}"
                                target="_blank"
                                class="qa-button"
                            >
                                View Playwright Screenshot
                            </a>
                        </div>
                        """
                    )
                )

            # Playwright traces
            traces = list(
                test_results_dir.rglob("trace.zip")
            )

            for trace in traces:

                relative_path = trace.relative_to(
                    report_dir
                ).as_posix()

                extras.append(
                    pytest_html.extras.html(
                        f"""
                        <div class="qa-evidence">
                            <a
                                href="{relative_path}"
                                target="_blank"
                                class="qa-button"
                            >
                                Open Playwright Trace
                            </a>
                        </div>
                        """
                    )
                )

        # Evidence path
        if screenshot_path.exists():
            extras.append(
                pytest_html.extras.text(
                    screenshot_path.relative_to(
                        report_dir
                    ).as_posix(),
                    name="Evidence Path",
                )
            )

    report.extras = extras


def pytest_html_results_table_row(report, cells):

    area_class = (
        "qa-ui"
        if report.area == "UI / Visual"
        else "qa-functional"
    )

    impact_class = (
        "qa-critical"
        if report.impact == "Critical / P1"
        else "qa-medium"
    )

    cells.insert(
        2,
        f"""
        <td>
            <span class="qa-badge {area_class}">
                {report.area}
            </span>
        </td>
        """,
    )

    cells.insert(
        3,
        f"""
        <td>
            <span class="qa-badge {impact_class}">
                {report.impact}
            </span>
        </td>
        """,
    )


def pytest_html_results_summary(prefix, summary, postfix):

    prefix.extend(
        [
            """
            <style>

                /* -----------------------------------------
                   NativeOffice QA report
                ----------------------------------------- */

                body {
                    font-family:
                        Inter,
                        -apple-system,
                        BlinkMacSystemFont,
                        "Segoe UI",
                        Arial,
                        sans-serif !important;

                    background: #f6f7fb !important;
                    color: #111827 !important;
                }

                h1 {
                    font-weight: 750 !important;
                    letter-spacing: -0.5px;
                }

                /* Metadata / summary area */

                .qa-header {
                    margin: 20px 0 24px;
                    padding: 22px 24px;
                    border: 1px solid #e5e7eb;
                    border-radius: 16px;
                    background: #ffffff;
                    box-shadow:
                        0 4px 18px rgba(15, 23, 42, 0.05);
                }

                .qa-title {
                    margin: 0 0 6px;
                    font-size: 20px;
                    font-weight: 750;
                    color: #111827;
                }

                .qa-subtitle {
                    margin: 0;
                    color: #6b7280;
                    font-size: 13px;
                }

                .qa-status {
                    display: inline-flex;
                    align-items: center;
                    gap: 7px;
                    margin-top: 14px;
                    padding: 7px 11px;
                    border-radius: 999px;
                    background: #f3f4f6;
                    color: #374151;
                    font-size: 12px;
                    font-weight: 700;
                }

                .qa-dot {
                    width: 7px;
                    height: 7px;
                    border-radius: 50%;
                    background: #22c55e;
                }

                /* Table */

                table {
                    border-radius: 14px !important;
                    overflow: hidden;
                    border: 1px solid #e5e7eb !important;
                    box-shadow:
                        0 4px 18px rgba(15, 23, 42, 0.04);
                }

                th {
                    background: #f9fafb !important;
                    font-size: 12px !important;
                    font-weight: 700 !important;
                    color: #6b7280 !important;
                }

                td {
                    font-size: 13px !important;
                }

                tr:hover td {
                    background: #fafafa !important;
                }

                /* QA badges */

                .qa-badge {
                    display: inline-block;
                    padding: 5px 9px;
                    border-radius: 999px;
                    font-size: 11px;
                    font-weight: 700;
                    white-space: nowrap;
                }

                .qa-ui {
                    background: #eef2ff;
                    color: #4338ca;
                }

                .qa-functional {
                    background: #ecfdf5;
                    color: #047857;
                }

                .qa-critical {
                    background: #fef2f2;
                    color: #b91c1c;
                }

                .qa-medium {
                    background: #fff7ed;
                    color: #c2410c;
                }

                /* Failure evidence */

                .qa-evidence {
                    margin: 8px 0;
                }

                .qa-button {
                    display: inline-block;
                    padding: 8px 12px;
                    border-radius: 9px;
                    background: #111827;
                    color: #ffffff !important;
                    text-decoration: none !important;
                    font-size: 12px;
                    font-weight: 650;
                    transition: opacity 0.15s ease;
                }

                .qa-button:hover {
                    opacity: 0.8;
                }

                code {
                    border-radius: 5px;
                    padding: 2px 5px;
                    background: #f3f4f6;
                }

            </style>

            <div class="qa-header">

                <div class="qa-title">
                    NativeOffice QA
                </div>

                <p class="qa-subtitle">
                    Automated Playwright / Pytest test execution
                </p>

                <div class="qa-status">
                    <span class="qa-dot"></span>
                    Failure evidence enabled
                </div>

            </div>
            """
        ]
    )