import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://tools.nativeoffice.online/")
    page.get_by_role("button", name="Recent").click()
    page.get_by_role("button", name="Templates", exact=True).click()
    page.get_by_role("button", name="Recent").click()
    page.get_by_role("button", name="Pinned").click()
    page.get_by_role("button", name="Shared with me").click()
    page.get_by_role("button", name="Trash").click()
    page.locator("div").filter(has_text="Folders").click()
    page.locator("#scroller").click()
    page.get_by_role("button", name="Home").click()
    page.get_by_role("button", name="Document Write, edit, and").click()
    page.get_by_role("paragraph").filter(has_text=re.compile(r"^$")).click()
    page.locator("#editor").get_by_role("textbox").fill("hello")
    page.get_by_role("link", name="NativeOffice").click()
    page.get_by_role("button", name="Spreadsheet Analyze data and").click()
    page.get_by_role("link", name="NativeOffice").click()
    page.get_by_role("button", name="Presentation Design stunning").click()
    page.get_by_text("Click to add title").click()
    page.get_by_text("Click to add title").click()
    page.get_by_text("Click to add title").dblclick()
    page.locator(".sl-editor").fill("native office")
    page.locator("#canvas").click()
    page.get_by_text("GU", exact=True).click()
    page.get_by_text("GU", exact=True).click()
    page.get_by_role("button", name="Hide the toolbar").click()
    page.get_by_role("banner").click()
    page.get_by_role("link", name="NativeOffice").click()
    page.get_by_role("button", name="View all").click()
    page.locator("#scroller").click()
    page.get_by_role("button", name="Workspace appearance").click()
    page.get_by_role("button", name="Soft Warm and calm").click()
    page.get_by_role("button", name="Done").click()
    page.get_by_role("button", name="Workspace appearance").click()
    page.get_by_role("button", name="Dark Low light focus").click()
    page.get_by_role("button", name="Done").click()
    page.get_by_role("button", name="Templates", exact=True).click()
    page.get_by_role("link", name="NativeOffice home").click()
    page.get_by_role("button", name="Close navigation").click()
    page.get_by_role("button", name="Create New").click()
    page.get_by_role("button", name="Poster").click()
    page.get_by_role("textbox", name="Presentation name").click()
    page.get_by_role("banner").click()
    page.get_by_role("banner").click()
    page.get_by_role("textbox", name="Presentation name").click()
    page.get_by_role("textbox", name="Presentation name").fill("antive")
    page.get_by_role("textbox", name="Presentation name").press("Enter")
    page.get_by_role("link", name="NativeOffice").click()
    page.get_by_role("link", name="NativeOffice home").click()
    page.get_by_role("link", name="NativeOffice home").click()
    page.locator("div").filter(has_text="NativeOffice").click()
    page.get_by_role("button", name="Close navigation").click()
