import re
from playwright.sync_api import Playwright,Page, sync_playwright, expect


def test_design(page: Page) -> None:

    page.goto("https://tools.nativeoffice.online/")
    page.get_by_role("button", name="Create new").click()
    page.get_by_role("button", name="Design A square visual canvas").click()
    page.locator(".sl-paint").click()
    page.get_by_role("button", name="Theme").click()
    page.get_by_role("button", name="Aa Simple Dark").click()
    page.get_by_role("button", name="Theme").click()
    page.get_by_role("button", name="Aa Focus").click()
    page.get_by_role("button", name="Background").click()
    page.get_by_role("button", name="#00ff00").click()
    page.get_by_role("button", name="Background").click()
    page.get_by_role("button", name="#45818e").click()
    page.get_by_role("button", name="Background").click()
    page.locator(".swatch-grid").click()
    page.get_by_role("button", name="Background").click()
    page.get_by_role("button", name="#c27ba0").click()
    page.get_by_role("button", name="New page", description="New slide").click()
    page.locator(".film-item.on > .film-thumb").click()
    page.get_by_role("button", name="Background").click()
    page.get_by_role("button", name="#00ffff").click()
    page.get_by_role("button", name="New page", description="New slide").click()
    page.get_by_role("button", name="AUTUMN 26 The Quiet Collection IN STORES FRIDAY Atelier Editorial product launch").click()
    page.get_by_role("button", name="New page", description="New slide").click()
    page.get_by_role("tab", name="Photos").click()
    page.get_by_role("tab", name="Elements").click()
    page.get_by_role("button", name="Rectangle", exact=True).click()
    page.get_by_role("button", name="Rounded rectangle").click()
    page.get_by_role("button", name="Ellipse").click()
    page.get_by_role("button", name="Triangle").click()
    page.get_by_role("button", name="Pentagon").click()
    page.get_by_role("button", name="Hexagon").click()
    page.get_by_role("button", name="Burst").click()
    page.get_by_role("button", name="Star", exact=True).click()
    page.get_by_role("button", name="Octagon").click()
    page.get_by_text("RectangleRounded").click()
    page.get_by_role("button", name="Crescent").click()
    page.get_by_role("button", name="Tag", exact=True).click()
    page.get_by_role("button", name="Arrow", description="Arrow").click()
    page.get_by_role("button", name="Arrow").nth(1).click()
    page.get_by_role("button", name="Double arrow").click()
    page.get_by_role("button", name="Plain").click()
    page.locator("html").click()
    page.get_by_role("tab", name="Design").click()
    page.get_by_role("tab", name="Text").click()
    page.get_by_role("button", name="Add a heading").click()
    page.get_by_role("button", name="Add a subheading").click()
    page.get_by_role("button", name="Add body text").click()
    page.get_by_role("button", name="Table").click()
    page.get_by_role("button", name="Cancel").click()
    page.get_by_role("button", name="Background").click()
    page.get_by_role("button", name="#ff0000").click()

    page.locator('a.brand[href="/"]').click()
    expect(page).to_have_url(
        "https://tools.nativeoffice.online/"
    )